name: Mark stale issues and pull requests daily

on:

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - name: Close out meeting issues
      uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: "This issue was opened for a while and has the meeting label. I will close this out assuming the issue is just for notes and has no open action items. Please remove the stale label if you'd like to keep this issue open."
        only-labels: "meeting"
        days-before-stale: 7
        days-before-close: 1
